# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bf0f1710fdda82889e0f782700497c62cd8720ea4a94c7318f4847b3b09dd07d3ea80cd1c6276b3fea3e36bda904505f7643cef743d3d4eba8974e572692a27

test:
  secret_key_base: c96e673c23079d64ba5231a252c07e29ecd94962ce4031d89a66190827f4dcb028195efa04f4434874bc07de811ff5e310a9e5e175c25595fde5323c4ee56e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
